CREATE TABLE IF NOT EXISTS logs (
  id BIGSERIAL PRIMARY KEY,
  src_ip VARCHAR(64) NOT NULL,
  dest_ip VARCHAR(64) NOT NULL,
  port INT NOT NULL,
  protocol VARCHAR(8) NOT NULL,
  bytes BIGINT NOT NULL,
  ts TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS alerts (
  id BIGSERIAL PRIMARY KEY,
  src_ip VARCHAR(64) NOT NULL,
  dest_ip VARCHAR(64) NOT NULL,
  port INT NOT NULL,
  reason VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
